---

# Ansible playbook for variable utilization
- hosts: dev
  vars_files:
    - variables.yml
  vars:
    variable1: "PlayBookValue"
  tasks:
    - name: Variable Value
      debug: msg="The value is {{ variable1 }}"
